from typing import TypedDict, Optional, List, Dict, Any, Annotated
from operator import add


def merge_dicts(left: dict, right: dict) -> dict:
    """Safely merges two dictionaries, preserving existing keys.

    Prevents LangGraph's default last-write-wins behavior from
    destroying per-test data when repair loops update individual tests.
    """
    if not left:
        return right
    if not right:
        return left
    merged = left.copy()
    merged.update(right)
    return merged


class TestPilotState(TypedDict):
    run_id: str
    project_id: str
    repo_url: str
    website_url: str
    status: str
    error: Optional[str]

    # Domain outputs generated by linear pipeline nodes
    auth_session: Optional[Dict[str, Any]]
    repo_analysis: Optional[Dict[str, Any]]
    page_inspections: Optional[List[Dict[str, Any]]]
    app_understanding: Optional[Dict[str, Any]]
    features: Optional[Dict[str, Any]]
    test_plan_doc: Optional[Dict[str, Any]]
    test_plan: Optional[List[Dict[str, Any]]]
    generated_tests: Optional[List[Dict[str, Any]]]
    execution_results: Optional[List[Dict[str, Any]]]
    pr_url: Optional[str]

    # LangGraph message history accumulator
    messages: Annotated[List[Dict[str, Any]], add]

    # --- Feedback loop fields (evaluation -> repair cycle) ---
    # Per-test verdict: { test_id: { verdict, category, reason, evidence } }
    evaluation_results: Annotated[Dict[str, dict], merge_dicts]
    # Per-test root cause: { test_id: { root_cause, explanation, repairable } }
    failure_analyses: Annotated[Dict[str, dict], merge_dicts]
    # Per-test repair attempt counter: { test_id: count }
    repair_attempts: Annotated[Dict[str, int], merge_dicts]
    # Per-test inconclusive retry counter: { test_id: count }
    inconclusive_retries: Annotated[Dict[str, int], merge_dicts]
    # Per-test repaired steps: { test_id: [step_dicts] }
    repaired_tests: Annotated[Dict[str, list], merge_dicts]
    # Accumulating list of suspected application bugs
    suspected_app_bugs: Annotated[List[dict], add]
    # Test IDs to execute in the next cycle (None = execute all)
    tests_to_execute: Optional[List[str]]

        # --- Live Verify (pre-execution selector validation) ---
    # Per-test live DOM verification report:
    # { test_id: { status, route, confirmedSteps, corrections, unconfirmedSelectors,
    #              executable, execution_status, verification_status } }
    live_verifications: Annotated[Dict[str, dict], merge_dicts]

    # --- Repair integrity (Fix 4/5) ---
    # Immutable snapshot of each scenario's ORIGINAL intent, captured by
    # playwright_gen before any execution/repair. A repair may change the
    # implementation (locator / timing / wait) but must never change the
    # semantic intent (what the test is testing).
    # { test_id: { test_id, test_name, feature, route, required_actions, expected_outcome } }
    test_intents: Annotated[Dict[str, dict], merge_dicts]
    # Per-test repair-integrity verdict:
    # { test_id: { status: "ACCEPTED" | "REJECTED", reason } }
    # A REJECTED repair is terminal for that test: it must not be re-scheduled
    # for execution nor repaired again.
    repair_statuses: Annotated[Dict[str, dict], merge_dicts]
