from typing import TypedDict, Optional, List, Dict, Any, Annotated
from operator import add

class TestPilotState(TypedDict):
    run_id: str
    project_id: str
    repo_url: str
    website_url: str
    status: str
    error: Optional[str]
    retry_count: int

    # Domain outputs generated by nodes
    auth_session: Optional[Dict[str, Any]]
    repo_analysis: Optional[Dict[str, Any]]
    test_plan: Optional[List[Dict[str, Any]]]
    generated_tests: Optional[List[Dict[str, Any]]]
    execution_results: Optional[List[Dict[str, Any]]]
    failure_analysis: Optional[Dict[str, Any]]
    pr_url: Optional[str]

    # LangGraph message history accumulator
    messages: Annotated[List[Dict[str, Any]], add]
